language: python
python:
  - "3.5"
env:
  - DJANGO=1.11.4
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python manage.py test -v 2 --exclude-tag 'functional-test' # tests unitarios
