language: python
python:
  - "3.5"
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
before_install:
  - ./functional_tests/install-geckodriver
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python manage.py test -v 2 --exclude-tag 'functional-test' # tests unitarios
  - python manage.py test -v 2 --tag 'functional-test'

# vim:set et sw=2 sts=-1 fdm=indent:
